### ISSUE TITLE
Handling trailing spaces in markdown

### ISSUE THREAD

**Issue by To1ne** [purcell/whitespace-cleanup-mode#14]
Cool package Steve!

At the moment I have `whitespace-cleanup` as a `before-save-hook`, but sometimes this is annoying with markdown files. From the [markdown spec](https://daringfireball.net/projects/markdown/syntax#p):

>When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

So my double whitespaces at the end of the line are eaten, when then shouldn't. So I was wondering if this package could handle them smarter.

It's not a real easy problem to tackle, so feel free to reject my feature request.

**Comment by purcell** [comment]
Note that `whitespace-cleanup` isn't part of this package -- it's a core Emacs function, which `whitespace-cleanup-mode` uses.

Whether trailing whitespace is trimmed is controlled by the `whitespace-style` variable, so I think that for your use case, you could use something like:

```el
(add-hook 'markdown-mode-hook
          (lambda () (setq-local whitespace-style (delq 'trailing whitespace-style))))
```

**Comment by To1ne** [comment]
Thanks!!!
