### ISSUE TITLE
Misleading description

### ISSUE THREAD

**Issue by E3D3** [purcell/whitespace-cleanup-mode#17]
Thank you for making & sharing `whitespace-cleanup-mode`. It is exactly what I was looking for, but I almost missed it because of the following wrong line in README.md:
> whitespace-cleanup-mode is a minor mode which calls whitespace-cleanup before saving the current buffer, **but only if the whitespace in the buffer was initially clean**.

Luckily I checked this in the source code and discovered that this mode can also work for *initially non-clean buffers* by setting a configuration option. I guess more people like to know this.

**Comment by purcell** [comment]
Thanks, I've clarified that!
