### ISSUE TITLE
New feature: preserve the current line position

### ISSUE THREAD

**Issue by rennsax** [purcell/whitespace-cleanup-mode#18]
Thanks for your contribution for this amazing package! Do you like the idea of also preserving the line position after the trailing newlines are truncated? Something like I did here https://github.com/rennsax/whitespace-cleanup-mode/commit/9f38eb82f1bec4262dff24a5474aaed03725cc6d.

The code may not be so robust, but it's enough for my daily usage. I have configured a frequent auto-save routine, so when I press some RET to insert several newlines, stop for a while, then the buffer is save, the trailing newlines are all removed, which is annoying. This commit prevent this behavior, and my cursor will always stay at the current line after saving the buffer.

Would you mind me send a PR after fully testing this feature?

**Comment by purcell** [comment]
Hmm, I'd probably prefer not to add that directly here, sorry, but I suspect you can achieve this easily in your config by adding an `around` advice function for `whitespace-cleanup`.
