### ISSUE TITLE
Enforcing final newline

### ISSUE THREAD

**Issue by bkhl** [purcell/whitespace-cleanup-mode#19]
I tried adding my own very similar mode to MELPA but was pointed to this one.

I kind of want to drop my own mode and switch to this now, since using `whitespace-mode` has some benefits over just using `delete-trailing-whitespace` as I did before.

However, there is one thing missing that my mode (https://git.sr.ht/~bkhl/trimspace-mode) has, which is enforcing a single trailing newline, when the final newline is missing.

It seems `whitespace-mode` has a setting to highlight this, but `whitespace-cleanup` has no method to fix it up. Do you know if I'm missing some way that I could get `whitespace-cleanup-mode` to enforce a single final newline?

**Comment by purcell** [comment]
Hi! If you want that behaviour, wouldn't you just set `require-final-newline` and allow the regular file-saving machinery to add that newline for you? Or have you tried that and found that `whitespace-cleanup` undoes it?

**Comment by bkhl** [comment]
I would want the same behaviour as in `trimspace-mode`, which is to consider files without a final newline "dirty" and not have the global minor mode enable cleanup in that case, and that when cleanup is enabled, that it also enforces the final newline, probably by automatically setting `require-final-newline` locally.

Considering that `whitespace-mode` already has a `missing-newline-at-eof` option set by default in `whitespace-styles` it should maybe be considered a bug in `whitespace-mode` that it doesn't do that already?

**Comment by purcell** [comment]
Yes, potentially. Perhaps work asking about in `emacs-devel`.

**Comment by purcell** [comment]
From my side I'm not super keen to make this mode do more than call `whitespace-cleanup`, because that's part of what makes its behaviour obvious/predictable, as well as keeping the implementation trivial.

**Comment by bkhl** [comment]
I suggested a change in whitesspace-mode and we'll see where it goes: https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-06/msg00818.html

**Comment by purcell** [comment]
Nice

**Comment by bkhl** [comment]
It looks from that thread like my bugfix will probably show up in Emacs 31.

However, while working on that I noticed several other bugs in whitespace.el which I don't have the energy to chase after, so will probably go back to the old simpler mode I made.

**Comment by purcell** [comment]
Nice, well done pushing for that fix.

Presumably you could also just advise `whitespace-cleanup`, and perform your own tweaks afterwards. Then `whitespace-cleanup-mode` would also work for the purposes of having a "clean up on save mode".

**Comment by bkhl** [comment]
Actually I found while working on this that `whitespace.el` itself has a `whitespace-action` variable, which allows an option to have `whitespace-mode` itself do cleanup on save, meaning you could entirely on that mode for the auto-cleanup, and only need an add-on for the "enable if already clean" functionality.

**Comment by purcell** [comment]
Interesting! I'll check that out sometime. I generally only enable `whitespace-mode` when I want to see the tabs/spaces etc. highlighted, so for me that's a separate use case.

**Comment by bkhl** [comment]
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2a7a7c6f697ac9699dec8b09f1cd2051247b2b45 has been merged now so will presumably show up in Emacs 31 unless someone finds issues with it.

**Comment by purcell** [comment]
Yay, that's great!
